### ISSUE TITLE
[1.21.1] Soul Surge NPE

### ISSUE THREAD

**Issue by jeremiahwinsley** [InnovativeOnlineIndustries/Industrial-Foregoing-Souls#13]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Industrial Foregoing Souls Version:**
industrial-foregoing-souls-1.21.1-1.10.1.jar

**Titanium Version:**
titanium-1.21-4.0.24.jar

**Crashlog If Applicable (Upload to pastebin/gist):**
https://gist.github.com/jeremiahwinsley/a20c4108ffd1119633d549a99acf8405

**Comment by Buuz135** [comment]
Should be fixed in this https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing-Souls/commit/a70ac268bff9cf7503b0054504d41253bdbe394a
