### ISSUE TITLE
[1.20.1] Visual bug due to connection changes when moving from 1.0.2 to 1.0.3

### ISSUE THREAD

**Issue by Ianthasys** [InnovativeOnlineIndustries/Industrial-Foregoing-Souls#2]
When using a world that was using the mod on an older version, after updating to the latest version, the soul surges visually look like they're connected to other surges on all sides but not on the side where the cables are.
![image](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing-Souls/assets/100318148/4b6773ab-7321-468b-8f6e-f8a020fdfdf7)
The issue seems to be purely visual and can be fixed via block updates or replacing cables.

**Comment by Buuz135** [comment]
Surges changed to allow connections between other surges. Update the blocks by placing a block next to them or breal them and place them again to update.
