### ISSUE TITLE
[1.20.1] Souls crashing server

### ISSUE THREAD

**Issue by sinnayuh** [InnovativeOnlineIndustries/Industrial-Foregoing-Souls#3]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Functional Storage Version:**
functionalstorage-1.20.1-1.2.8

**Titanium Version:**
titanium-1.20.1-3.8.25

**Crashlog If Applicable (Upload to pastebin/gist):**
https://mclo.gs/BjhmJ7s

**Comment by Micaxs** [comment]
Had a similar issue in ATM9 modpack:

https://mclo.gs/Gr3J9vt

Believe networkManager is null within the given file on the given line in the crash report. Might want to add a check if its not null I suppose.
